apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-controller.fullname" . }}
  labels:
    app: {{ template "postgres-controller.name" . }}
    chart: {{ template "postgres-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "postgres-controller.name" . }}
    helm.sh/chart: {{ include "postgres-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  db_password: {{ .Values.postgres.password | b64enc | quote }}
type: Opaque
