apiVersion: postgresql.org/v1
kind: PostgresDatabase
metadata:
  name: app3
spec:
  dbName: 
    value: db3
  dbRoleName: 
    value: user3
  dbRolePassword: 
    value: swordfish
  onDeletion:
    # Whether to drop the databse when the resource is deleted
    dropDB: false
    # Whether to drop the role when the resource is deleted
    dropRole: false
