apiVersion: postgresql.org/v1
kind: PostgresDatabase
metadata:
  name: app1
spec:
  dbName: db1
  dbRoleName: user1
  dbRolePassword: swordfish
  onDeletion:
    # Whether to drop the databse when the resource is deleted
    dropDB: false
    # Whether to drop the role when the resource is deleted
    dropRole: false
